### ISSUE TITLE
Path-generation aint pluralized

### ISSUE THREAD

**Issue by fredrikhenne** [kfaustino/rails-templater#13]
After installing the gem and trying to get a new app up and running I'm greeted with the following:

The template [/home/fredrik/.rvm/gems/ree-1.8.7-2010.02/gems/rails_templater-0.2.0/lib/template_framework/template_runner.rb] could not be loaded. Error: No such file or directory - /home/fredrik/.rvm/gems/ree-1.8.7-2010.02/gems/rails_templater-0.2.0/lib/template_framework/template/git/gitignore

So after downloading the source and running the specs there is one failing:

1) RailsTemplater::Templater generates a snippet path
     Failure/Error: subject.snippet_path("cucumber").should == File.expand_path('snippets/cucumber', TEMPLATE_FRAMEWORK_PATH)
       expected: "/home/fredrik/www/rails-templater/lib/template_framework/snippets/cucumber"
            got: "/home/fredrik/www/rails-templater/lib/template_framework/snippet/cucumber" (using ==)
     # ./spec/rails_templater/templater_spec.rb:17

The error is clearly shown and boils down to the use of pluralize at https://github.com/kfaustino/rails-templater/blob/master/lib/rails_templater/templater.rb#L38 - which if I've understood correctly is a rails-method and not in Ruby-core?

Easy solution would be to just append "s" to the strings, effectively bypassing the faulty paths while still retaining functionality.

For the record I'm running Arch Linux with user-install RVM - Rails is installed and functioning.

**Comment by guilleiguaran** [comment]
I can confirm this bug, I'm getting this error since yesterday when I upgrade to Rails 3.0.4

**Comment by fredrikhenne** [comment]
Been a bit of time since I used the pull request function so there was another issue created too.  https://github.com/kfaustino/rails-templater/issues#issue/14 I've commited my proposed solution and done a pull request.

**Comment by fredrikhenne** [comment]
And there I accidently closed the issue _sigh_. Guess one should not press buttons before reading.

**Comment by kfaustino** [comment]
Weird issue. The pluralize method is being included via activesupport in https://github.com/kfaustino/rails-templater/blob/master/lib/rails_templater.rb#L1. I tested against Rails 3.0.3 and 3.0.4 and it seems like something has changed in the inflector between releases.

Thanks for the fix :)
