### ISSUE TITLE
Github redirecting to SSL

### ISSUE THREAD

**Issue by curthasselschwert** [kfaustino/rails-templater#3]
Thanks for sharing this great template. I have one problem: when I use this template for a new Rails app, I get an error when it comes to the JQuery recipe. open-uri complains that redirects are not allowed, because the recipe is trying to get <code>http://github.com/rails/jquery-ujs/raw/master/src/rails.js</code> and gets redirected to <code>https://github.com/rails/jquery-ujs/raw/master/src/rails.js</code>. If I simply change the URL in the recipe to <code>https://github.com/rails/jquery-ujs/raw/master/src/rails.js</code> I get an error that it's not in my sources. Any ideas?

**Comment by kfaustino** [comment]
I am going to make an update to Thor and hopefully they accept my pull request. 

Until then, I've updated rails.js to pull from a local template in commit e01420ca378e3de28bf9

**Comment by curthasselschwert** [comment]
Thanks for your great work on this. It's been a big help. I've noticed one other strange thing. When I use the template to create a new app, I get a notice that bson_ext is not installed when I run my Cucumber features. I don't get the warning when I create an app from scratch and follow the steps you outlined on your blog. It's in my Gemfile and installed when I run <code>bundle install</code>. In case it helps, I'm using RVM to manage my ruby installs. Have any thoughts on why this might be?

**Comment by kfaustino** [comment]
I'll take a look tonight

**Comment by kfaustino** [comment]
Do a git pull on rails-templater. Migrated over to jquery-rails and also added a whole bunch of little fixes.

In regards to your issue, if you are using the latest mongoid beta, just add bson_ext version 1.1.2 to your Gemfile to remove that warning.
