### ISSUE TITLE
RVM support

### ISSUE THREAD

**Issue by mcculloughsean** [kfaustino/rails-templater#5]
Could you add support to create an rvmrc and then use that environment to install the gems?

**Comment by kfaustino** [comment]
I will try and get out that feature soon

**Comment by dmasur** [comment]
+1 that would be nice if there is a gemset for the app too.

**Comment by kfaustino** [comment]
With the introduction of [rbenv](https://github.com/sstephenson/rbenv), I have decided to make the assumption that the user has setup their environment already. So if you are running RVM and gemsets, create the gemset before running templater.
