### ISSUE TITLE
Cucumber is Acceptance Testing

### ISSUE THREAD

**Issue by yfeldblum** [kfaustino/rails-templater#9]
Cucumber is more accurately categorized as a tool for "acceptance testing" than as a tool for "integration testing".

Integration testing is testing the system with its various sub-components integrated together. Integration testing is contrasted with unit testing, where each sub-component of a system is tested in isolation from all other sub-components.

Acceptance testing is different. From Wikipedia (http://en.wikipedia.org/wiki/Acceptance_testing):

> Acceptance testing generally involves running a suite of tests on the completed system.
> 
> Acceptance Tests/Criteria (in Agile Software Development) are usually created by business customers and expressed in a business domain language.

This describes Cucumber features very well.

**Comment by dmasur** [comment]
Sry I think Cucumber can be both. I use it for myself as developer for integration testing. I dont know many ppl who really use it only for expressing only to communicate with there business partners and use something else like Test::Unit for integration tests.
